# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TypstD2Mcp < Formula
  desc "MCP server for AI-assisted Typst documentation with D2 diagrams"
  homepage "https://github.com/dlouwers/typst-d2-mcp"
  version "1.2.1"
  license "MIT"

  depends_on "d2"
  depends_on "typst"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.2.1/typst-d2-mcp_1.2.1_darwin_amd64.tar.gz"
      sha256 "7ead29ebd2c78f52468a70f7b77b350c2d0f89e93a2653c72cb9aa48fad675a8"

      define_method(:install) do
        bin.install "typst-d2-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.2.1/typst-d2-mcp_1.2.1_darwin_arm64.tar.gz"
      sha256 "404866141a4ac32f609c663f16c1dcb9ba2c073416f82d420a2be2b2707f7af5"

      define_method(:install) do
        bin.install "typst-d2-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.2.1/typst-d2-mcp_1.2.1_linux_amd64.tar.gz"
      sha256 "cd89edf1c6529fbcd9f0ad7fd12a2cc9b30ca1289b6fa9a44b950b3a32265ceb"
      define_method(:install) do
        bin.install "typst-d2-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.2.1/typst-d2-mcp_1.2.1_linux_arm64.tar.gz"
      sha256 "b9cc514fc281c5fb2441c214b55b82c02e7518354e8374791d1b53eecf8659ea"
      define_method(:install) do
        bin.install "typst-d2-mcp"
      end
    end
  end

  test do
    system "#{bin}/typst-d2-mcp", "--help"
  end
end
