# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TypstD2Mcp < Formula
  desc "MCP server for AI-assisted Typst documentation with D2 diagrams"
  homepage "https://github.com/dlouwers/typst-d2-mcp"
  version "2.0.0"
  license "MIT"

  depends_on "d2"
  depends_on "typst"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v2.0.0/typst-d2-mcp_2.0.0_darwin_amd64.tar.gz"
      sha256 "b6cf86082a48a1720eb131b9fc4b72dee4426c0f1fb114166d9cb8291a0806a1"

      define_method(:install) do
        bin.install "typst-d2-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v2.0.0/typst-d2-mcp_2.0.0_darwin_arm64.tar.gz"
      sha256 "f7ac020ccd81c9376b570edcdeef38761cc2294e7404b4eac736fd1c7ab7a9c7"

      define_method(:install) do
        bin.install "typst-d2-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v2.0.0/typst-d2-mcp_2.0.0_linux_amd64.tar.gz"
      sha256 "fae62cdf87709f2ec1e695fb23da7a5c39d3c8f42ec561ea885efc46c6b9ed3f"
      define_method(:install) do
        bin.install "typst-d2-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v2.0.0/typst-d2-mcp_2.0.0_linux_arm64.tar.gz"
      sha256 "63caffdf6a3133c5de3f09c8cbd69b19ae823dc159578be8a2c7acd65f35f1c4"
      define_method(:install) do
        bin.install "typst-d2-mcp"
      end
    end
  end

  test do
    system "#{bin}/typst-d2-mcp", "--help"
  end
end
