# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TypstD2Prep < Formula
  desc "Preprocessor for D2 diagrams in Typst documents"
  homepage "https://github.com/dlouwers/typst-d2-mcp"
  version "1.2.2"
  license "MIT"

  depends_on "d2"
  depends_on "typst"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.2.2/typst-d2-mcp_1.2.2_darwin_amd64.tar.gz"
      sha256 "b84babeaf2bbe4ed755661aeb7de54b73d2e75b4054fb0b88e9dfc5bf2807d30"

      define_method(:install) do
        bin.install "typst-d2-prep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.2.2/typst-d2-mcp_1.2.2_darwin_arm64.tar.gz"
      sha256 "1b9ccbb15452f6552a99b18272cdd0b3bd322be3b83c1b19195d980cdbda6c69"

      define_method(:install) do
        bin.install "typst-d2-prep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.2.2/typst-d2-mcp_1.2.2_linux_amd64.tar.gz"
      sha256 "7b07b91640511b1e258e5a4b0274a0a70a4a1146890398f14f5673e01364f0f9"
      define_method(:install) do
        bin.install "typst-d2-prep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.2.2/typst-d2-mcp_1.2.2_linux_arm64.tar.gz"
      sha256 "4e625ce01d283716dd4ad6cfcb6e1042686d133f88358e55a29b46dfe4323300"
      define_method(:install) do
        bin.install "typst-d2-prep"
      end
    end
  end

  test do
    system "#{bin}/typst-d2-prep", "version"
  end
end
