# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TypstD2Prep < Formula
  desc "Preprocessor for D2 diagrams in Typst documents"
  homepage "https://github.com/dlouwers/typst-d2-mcp"
  version "1.0.0"
  license "MIT"

  depends_on "d2"
  depends_on "typst"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.0.0/typst-d2-mcp_1.0.0_darwin_amd64.tar.gz"
      sha256 "2dd064860394195a8322fc7df0f2383e16ee5b36e485d9060b2f89a9a9a7d4d9"

      define_method(:install) do
        bin.install "typst-d2-prep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.0.0/typst-d2-mcp_1.0.0_darwin_arm64.tar.gz"
      sha256 "cb140d5cc36345021ec79dd8adf4cb006e3b9d6f47f7d4d7aed9e189c5f7c0e9"

      define_method(:install) do
        bin.install "typst-d2-prep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.0.0/typst-d2-mcp_1.0.0_linux_amd64.tar.gz"
      sha256 "e84557e5387e0d48caab5d8c7bd040cc50949f679644bed1199afe79b37d2808"
      define_method(:install) do
        bin.install "typst-d2-prep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/typst-d2-mcp/releases/download/v1.0.0/typst-d2-mcp_1.0.0_linux_arm64.tar.gz"
      sha256 "04dede03c2144d1e8177a896fb484495308dbc3712a66f40240f0670dfc1e698"
      define_method(:install) do
        bin.install "typst-d2-prep"
      end
    end
  end

  test do
    system "#{bin}/typst-d2-prep", "version"
  end
end
